Database:
  Type: SQLITE
  IdentifierType: UUID
  Hostname: localhost
  Port: 3306
  Database: database
  Username: admin
  Password: password
Listeners:
  ComplexListeners:
    Discord-Cmd:
      Register: false
      Values:
        Message: '&7Click here to join our discord server!'
        URL: 'https://discord.gg/invite'
    Player-Spectate-On-Death:
      Register: false
      Values:
        Length: 5
        Blob-Messages:
          - Spectator.Oof
          - Spectator.Wasted
          - Spectator.Dead
          - Spectator.Keep-Alive
    Alternative-Saving:
      Register: false
      Values:
        Player-Serializer: SIMPLE
        Inventory-Driver: DEFAULT
        Welcome-Players:
          Register: true
          Message: System.Welcome
          Inventory-Is-Soul: false
  TinyListeners:
    Drop-Non-Soul-On-Death: false
    Player-Keep-Experience-On-Death: false
    Entities-Clear-Drops-On-Death: false
    Cancel-Entity-Drop-Item: false
    Translate-On-Pickup: false
    Translate-On-Locale-Switch: false
    Translate-On-Join: false
    Translate-On-Alternative-Saving-Join: false
  SimpleListeners:
    Remove-Junk:
      Register: false
      #TagSet that considers items as junk
      TagSet: BlobRP.Junk
    Respawn-Inventory:
      Register: false
      MetaBlobInventory: WelcomeInventory
    Prevent-Ice-Formation:
      Register: false
      World-Whitelist:
        - world
    Remove-Player-Hunger:
      Register: false
      Requires-Permission: false
    Player-Drop-Experience-On-Death:
      Register: false
      Amount: 0
    Entities-Drop-Experience-On-Death:
      Register: false
      Amount: 0
    Sell-Articles-Event:
      Register: true
      DefaultPrice: 1
    Manage-Sell-Articles:
      Register: true
      Permission-Multiplier: false
    Merchants:
      Register: true
      # If you wish to remove the message, leave it as ''
      Bought-Message: Economy.Received-Withdrawal
    Merchants-View:
      Register: true
      Add: BlobRP.Merchants-View
    Welcome-Players:
      Register: false
      # If you wish to remove the message, leave it as ''
      Message: System.Welcome
    Force-Gamemode:
      Register: false
      Gamemode: ADVENTURE
    Global-Slow-Digging:
      Register: false
      Level: 1
    On-Join-Message:
      Register: false
      # If you wish to remove the message, leave it as ''
      Message: System.Join
    On-Quit-Message:
      Register: false
      # If you wish to remove the message, leave it as ''
      Message: System.Quit
    Kill-Message-Weapon:
      Register: false
      Message: Event.PlayerKillPlayer
    Player-Death-Message:
      Register: false
      # If you wish to remove the message, leave it as ''
      Message: Event.PlayerDeathEvent