Database:
  Type: SQLITE
  IdentifierType: UUID
  Host: localhost
  Port: '3306'
  Database: database
  Username: admin
  Password: password
ComplexListeners:
  Discord-Cmd:
    Register: false
    Values:
      Message: '&7Click here to join our discord server!'
      URL: 'https://discord.gg/invite'
  Player-Spectate-On-Death:
    Register: false
    Values:
      Length: 5
      Blob-Messages:
        - Spectator.Oof
        - Spectator.Wasted
        - Spectator.Dead
        - Spectator.Keep-Alive
  Alternative-Saving:
    Register: false
    Values:
      Player-Serializer: SIMPLE
      Inventory-Driver: DEFAULT
      Welcome-Players:
        Register: true
        Message: System.Welcome
        Inventory-Is-Soul: false
Listeners:
  Ice-Formation:
    Register: true
    World-Whitelist:
      - world
  Remove-Player-Hunger:
    Register: false
    Requires-Permission: false
  Drop-Non-Soul-On-Death: false
  Player-Drop-Experience-On-Death:
    Register: false
    Amount: 0
  Player-Keep-Experience-On-Death: false
  Entities-Drop-Experience-On-Death:
    Register: false
    Amount: 0
  Entities-Clear-Drops-On-Death: false
  Entity-Drop-Item: true
  Sell-Articles-Event:
    Register: true
    DefaultPrice: 1
  Manage-Sell-Articles:
    Register: true
    Permission-Multiplier: false
  Merchants:
    Register: true
    # If you wish to remove the message, leave it as ''
    Bought-Message: Economy.Received-Withdrawal
  Merchants-View:
    Register: true
    Add:
      - ''
      - '&7Price &r%format%'
  Welcome-Players:
    Register: true
    # If you wish to remove the message, leave it as ''
    Message: System.Welcome
  Force-Gamemode:
    Register: false
    Gamemode: ADVENTURE
  Global-Slow-Digging:
    Register: false
    Level: 1
  On-Join-Message:
    Register: true
    # If you wish to remove the message, leave it as ''
    Message: System.Join
  On-Quit-Message:
    Register: true
    # If you wish to remove the message, leave it as ''
    Message: System.Quit
  Kill-Message-Weapon:
    Register: false
    Message: '&7%attacker% &c☠ %victim%'
  Player-Death-Message:
    Register: false
    # If you wish to remove the message, leave it as ''
    Message: '&c☠ %victim%'