Database:
  Type: SQLITE
  IdentifierType: UUID
  Host: localhost
  Port: '3306'
  Database: database
  Username: admin
  Password: password
ComplexListeners:
  DiscordCmd:
    Register: false
    Values:
      Message: '&7Click here to join our discord server!'
      URL: 'https://discord.gg/invite'
  PlayerSpectateOnDeath:
    Register: false
    Values:
      Length: 5
      BlobMessages:
        - Spectator.Oof
        - Spectator.Wasted
        - Spectator.Dead
        - Spectator.Keep-Alive
  AlternativeSaving:
    Register: false
    Values:
      PlayerSerializer: SIMPLE
      InventoryDriver: DEFAULT
      WelcomePlayers:
        Register: true
        Message: System.Welcome
        Inventory-Is-Soul: false
Listeners:
  IceFormation:
    Register: true
    WorldWhitelist:
      - world
  PlayerHunger:
    Register: true
    RequiresPermission: false
  DropNonSoulOnDeath:
    Register: false
    Drop: true
  PlayerDropExperienceOnDeath:
    Register: true
    Amount: 0
  PlayerKeepExperienceOnDeath:
    Register: true
    Keep: false
  EntitiesDropExperienceOnDeath:
    Register: true
    Amount: 0
  EntitiesClearDropsOnDeath:
    Register: true
    Clear: true
  EntityDropItem:
    Register: true
    Cancel: true
  SellArticlesEvent:
    Register: true
    DefaultPrice: 1
  ManageSellArticles:
    Register: true
    PermissionMultiplier: false
  Merchants:
    Register: true
    # If you wish to remove the message, leave it as ''
    BoughtMessage: Economy.Received-Withdrawal
  MerchantsView:
    Register: true
    Add:
      - ''
      - '&7Price &r%format%'
  WelcomePlayers:
    Register: true
    # If you wish to remove the message, leave it as ''
    Message: System.Welcome
  ForceGamemode:
    Register: false
    Gamemode: ADVENTURE
  Global-Slow-Digging:
    Register: false
    Level: 1
  OnJoinMessage:
    Register: true
    # If you wish to remove the message, leave it as ''
    Message: System.Join
  OnQuitMessage:
    Register: true
    # If you wish to remove the message, leave it as ''
    Message: System.Quit
  KillMessageWeapon:
    Register: false
    Message: '&7%attacker% &c☠ %victim%'
  PlayerDeathMessage:
    Register: false
    # If you wish to remove the message, leave it as ''
    Message: '&c☠ %victim%'