Database:
  Type: SQLITE
  IdentifierType: UUID
  Hostname: localhost
  Port: 3306
  Database: database
  Username: admin
  Password: password
Settings:
  Pressure:
    Enabled: false
    Health-To-Pressure: 14.6959
    Tolerance: 29.3918
    Worlds: { }
  RoleplayWarp:
    # If disabled, the UI cannot be opened
    Enabled: false
    # If false, it will check for warmup on each RoleplayWarp individually
    Use-Global-Warmup: true
    # Warmup in ticks
    Global-Warmup: 100
Listeners:
  ComplexListeners:
    PhatLootChest-Requires-Key:
      Register: false
      Values: [ ]
    BlobDesign-Custom-Mining:
      Register: false
      Values:
        BLOCK_DISPLAY: { }
        ITEM_DISPLAY: { }
    Discord-Cmd:
      Register: false
      Values:
        Message: '&7Click here to join our discord server!'
        URL: 'https://discord.gg/invite'
    Player-Spectate-On-Death:
      Register: false
      Values:
        Length: 5
        Blob-Messages:
          - Spectator.Oof
          - Spectator.Wasted
          - Spectator.Dead
          - Spectator.Keep-Alive
    Alternative-Saving:
      Register: false
      Values:
        Player-Serializer: SIMPLE
        Inventory-Driver: DEFAULT
        Welcome-Players:
          Register: true
          Message: System.Welcome
          Inventory-Is-Soul: false
    PhatLoots-Holograms:
      Register: false
      Values:
        X: 0.5
        Y: 1.5
        Z: 0.5
  TinyListeners:
    # If true, it will transfer funds from BlobTycoon to Economy plugin if a sale failed and had funds
    BlobTycoon-ShopArticle-Transfer-Funds: false
    # If true, drops non 'Soul' items on death, even if keepInventory is true
    Drop-Non-Soul-On-Death: false
    # If true, players will keep their experience on death, similar to keepInventory gamerule
    Player-Keep-Experience-On-Death: false
    # If true, entities drops will be cleared on death
    Entities-Clear-Drops-On-Death: false
    # If true, it will cancel entities from dropping items, like eggs from chickens
    Cancel-Entity-Drop-Item: false
    # Examples: Snow melting due to being near a light source, ice melting due to being near a light source, fire burning out after time, without destroying fuel block, coral fading to dead coral due to lack of water, Turtle Egg bursting when a turtle hatches
    Cancel-Block-Fade: false
    # Tries to apply translatable items to weapon mechanics items
    Apply-TranslatableItems-To-WeaponMechanics: false
    # If true, when opening a PhatLootChest, it will play a smooth break animation.
    PhatLootChest-Smooth-Break-Animation: false
    # Translates all translatable items from a PhatLoot
    Translate-On-PhatLoot: false
    # Translates a translatable item on pickup
    Translate-On-Pickup: false
    # Translates all translatable items in inventory when changing locale
    Translate-On-Locale-Switch: false
    # Translates all translatable items on join
    Translate-On-Join: false
    # Translates all translatable items on alternative saving join
    Translate-On-Alternative-Saving-Join: false
  SimpleListeners:
    Disable-Natural-Spawn:
      Register: false
      Mobs:
        - CREEPER
    Remove-Junk:
      Register: false
      #TagSet that considers items as junk
      TagSet: BlobRP.Junk
    Respawn-Inventory:
      Register: false
      MetaBlobInventory: WelcomeInventory
    Prevent-Ice-Formation:
      Register: false
      World-Whitelist:
        - world
    Remove-Player-Hunger:
      Register: false
      Requires-Permission: false
    Player-Drop-Experience-On-Death:
      Register: false
      Amount: 0
    Entities-Drop-Experience-On-Death:
      Register: false
      Amount: 0
    Sell-Articles-Event:
      Register: true
      DefaultPrice: 1
    Manage-Sell-Articles:
      Register: true
      Permission-Multiplier: false
    Merchants:
      Register: true
      # If you wish to remove the message, leave it as ''
      Bought-Message: Economy.Received-Withdrawal
    Merchants-View:
      Register: true
      Add: BlobRP.Merchants-View
    Welcome-Players:
      Register: false
      # If you wish to remove the message, leave it as ''
      Message: System.Welcome
    Force-Gamemode:
      Register: false
      Gamemode: ADVENTURE
    Global-Slow-Digging:
      Register: false
      Level: 1
    On-Join-Message:
      Register: false
      # If you wish to remove the message, leave it as ''
      Message: System.Join
    On-Quit-Message:
      Register: false
      # If you wish to remove the message, leave it as ''
      Message: System.Quit
    Kill-Message-Weapon:
      Register: false
      Message: Event.PlayerKillPlayer
    Player-Death-Message:
      Register: false
      # If you wish to remove the message, leave it as ''
      Message: Event.PlayerDeathEvent