Listeners:
  DropNonSoulOnDeath:
    Register: true
    Drop: true
  PlayerDropExperienceOnDeath:
    Register: true
    Amount: 0
  PlayerKeepExperienceOnDeath:
    Register: true
    Keep: false
  EntitiesDropExperienceOnDeath:
    Register: true
    Amount: 0
  EntitiesClearDropsOnDeath:
    Register: true
    Clear: true
  EntityDropItem:
    Register: true
    Cancel: true
  SellArticlesEvent:
    Register: true
    DefaultPrice: 1
  ManageSellArticles:
    Register: true
    PermissionMultiplier: false
  Merchants:
    Register: true
    BoughtMessage: Economy.Received-Withdrawal
  MerchantsView:
    Register: true
    Add:
      - ''
      - '&7Price &r%format%'
  WelcomePlayers:
    Register: true
    Message: System.Welcome