Listeners:
  DropNonSoulOnDeath:
    Register: true
    Drop: true
  PlayerDropExperienceOnDeath:
    Register: true
    Amount: 0
  PlayerKeepExperienceOnDeath:
    Register: true
    Keep: false
  EntitiesDropExperienceOnDeath:
    Register: true
    Amount: 0
  EntitiesClearDropsOnDeath:
    Register: true
    Clear: true
  EntityDropItem:
    Register: true
    Cancel: true