name: BlobRP
version: ${project.version}.${buildNumber}
main: us.mytheria.blobrp.BlobRP
api-version: 1.16
depend: [ BlobLib ]
authors: [ anjoismysign ]
commands:
  discord:
    description: discordcmd
  shoparticle:
    description: made with BlobLib
  cashreward:
    description: made with BlobLib
  itemstackreward:
    description: made with BlobLib
  permissionreward:
    description: made with BlobLib
  trophyrequirement:
    description: made with BlobLib
  blobsoul:
    description: info soul
    aliases: [ soul ]
  blobmerchant:
    description: info merchant
    aliases: [ merchant ]