name: BlobRP
version: ${project.version}
main: io.github.anjoismysign.blobrp.BlobRP
api-version: 1.21
depend: [ BlobLib ]
authors: [ anjoismysign ]
softdepend:
  - WeaponMechanics
  - DecentHolograms
  - FancyHolograms
  - PhatLoots
loadbefore:
  - BlobTycoon
commands:
  discord:
    description: discordcmd
  shoparticle:
    description: made with BlobLib
  blobsoul:
    description: info soul
    aliases: [ soul ]
  blobmerchant:
    description: info merchant
    aliases: [ merchant ]
  roleplayrecipe:
    description: info recipe
    aliases: [ rprecipe, recipe ]
  roleplaywarps:
    description: info warps
    aliases: [ rwarps, warps, warp ]