name: BlobRP
version: ${project.version}
main: us.mytheria.blobrp.BlobRP
api-version: 1.17
depend: [ BlobLib ]
authors: [ anjoismysign ]
softdepend:
  - WeaponMechanics
  - DecentHolograms
  - FancyHolograms
  - PhatLoots
loadbefore:
  - BlobTycoon
commands:
  discord:
    description: discordcmd
  shoparticle:
    description: made with BlobLib
  cashreward:
    description: made with BlobLib
  itemstackreward:
    description: made with BlobLib
  permissionreward:
    description: made with BlobLib
  trophyrequirement:
    description: made with BlobLib
  blobsoul:
    description: info soul
    aliases: [ soul ]
  blobmerchant:
    description: info merchant
    aliases: [ merchant ]
  roleplayrecipe:
    description: info recipe
    aliases: [ rprecipe, recipe ]