name: BlobRP
version: ${project.version}.${buildNumber}
main: us.mytheria.blobrp.BlobRP
api-version: 1.16
depend: [ BlobLib ]
authors: [ anjoismysign ]
commands:
  shoparticle:
    description: info shoparticle
  blobsoul:
    description: info soul
    aliases: [ soul ]